# Generated by Django 4.2.2 on 2023-08-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='scname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='king', to='app.school'),
        ),
    ]
